set(APP_SOURCES src/main.cpp)


set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_BINARY_DIR}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_BINARY_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_BINARY_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}")


add_executable(xethd ${APP_SOURCES})
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a;.la;.lib;.so;.dll")


target_include_directories(
    xethd
    PUBLIC
    ${Boost_INCLUDE_DIRS}
    ${JSONCPP_INCLUDE_DIR}
    ${PROJECT_SOURCE_DIR}/src
    ${ETHCRYPTO_INCLUDE_DIRS}
    ${ETHRPC_INCLUDE_DIRS}
    ${ETHSTEALTH_LIBRARIES}
    ${BITPROFILE_INCLUDE_DIRS}
)

target_link_libraries(xethd
    xethdlib
    ${BITPROFILE_LIBRARIES}
    ${ETHSTEALTH_LIBRARIES}
    ${ETHRPC_LIBRARIES}
    ${ETHCRYPTO_LIBRARIES}

    ${JSONCPP_LIBRARY}
    ${Boost_SYSTEM_LIBRARY}
    ${Boost_THREAD_LIBRARY}
    ${Boost_PROGRAM_OPTIONS_LIBRARY}
    ${Boost_FILESYSTEM_LIBRARY}
    ${Boost_RANDOM_LIBRARY}
    ${Boost_REGEX_LIBRARY}
    ${Boost_DATE_TIME_LIBRARY}
    ${Boost_CHRONO_LIBRARY}
    ${LEVELDB_LIBRARIES}
    ${CMAKE_THREAD_LIBS_INIT} 
)


if(GMP_LIBRARIES)
    target_link_libraries(xethd ${GMP_LIBRARIES})
endif()


